
program: main.py
name: bacon_snoop_facotry
project: bacon_snoop_facotry
description: generating Snoop Dogg using BACON
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss2_view
  goal: minimize
parameters:
  obj_path: 
    value: data/source_meshes/person.obj
  prompt: 
    values:  ["a photo of Snoop Dogg wearing a black shirt and a golden belt.", "a picture of Snoop Dogg with a purple shirt and golden shoes.", "A photo of Snoop Dogg wearing green shorts."]
  output_dir: 
    value: results/demo/person/output
  n_iter: 
    value: 2000
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  clipavg: 
    value: 'view'
  geoloss: 
    values: [0, 1]
  lr_decay: 
    values: [1.0, 0.92]
  learning_rate:
    values: [0.001, 0.0005, 0.0002]
  normratio:
    values: [0.05, 0.02, 0.005]
  seed:
    values: [2022, 1990, 1991]
  pe: 
    value: 0
  frontview_std: 
    values: [4.0]
  frontview_elev_std: 
    values: [1.0, 2.0, 4.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 0
  model_name:
    values: ['RN50', 'RN50x4', 'RN50x16']
  divers_batch_aug:
    values: [0, 1]
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    values: [4, 2]
  colordepth:
    values: [4, 2]
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    value: MultiscaleBACON
  depth:
    values: [8, 6]
  width:
    values: [512, 256]
  sigma:
    values: [768, 384, 192, 96]
  n_views:
    values: [5, 10]
  background_image_mode:
    values: ['change_per_iter', 'white', 'checkerboard', 'random_noise']