
program: main.py
name: baconnormal_snoop_XLfacotry
project: baconnormal_snoop_XLfacotry
description: generating Snoop Dogg using BACON and Xlarge CLIP
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss2_view
  goal: minimize
parameters:
  obj_path: 
    value: data/source_meshes/person.obj
  prompt: 
    values:  ["a picture of Snoop Dogg wearing a purple shirt and golden shoes.", "a photo of Snoop Dogg wearing a black shirt and a golden belt."]
  output_dir: 
    value: results/demo/person/output
  n_iter: 
    value: 2000
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  clipavg: 
    value: 'view'
  geoloss: 
    values: [0]
  lr_decay: 
    values: [0.95]
  learning_rate:
    values: [0.0005]
  normratio:
    values: [0.01, 0.025, 0.005]
  seed:
    values: [2022, 1990]
  pe: 
    value: 0
  frontview_std: 
    values: [4.0]
  frontview_elev_std: 
    values: [5.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 0
  model_name:
    values: ['RN50x64']
  divers_batch_aug:
    values: [1]
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    values: [3]
  colordepth:
    values: [3]
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    values: [BACON, MultiscaleBACON]
  depth:
    values: [8]
  width:
    values: [256]
  sigma:
    values: [448]
  n_views:
    values: [6] # 10 significantly improves the performance of the model.
  background_image_mode:
    values: ['change_per_iter']