
program: main.py
name: NSF_sweep_snoop
project: NSF_BACON_sweep_snoop
description: comparing NSF vs BACON on snoop dogg
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss2_view
  goal: minimize
parameters:
  obj_path: 
    value: data/source_meshes/person.obj
  prompt: 
    values:  ["a 3D rendering of Snoop Dogg wearing a hoodie.", "Snoop Dogg wearing a jacket."]
  output_dir: 
    value: results/demo/person/output
  n_iter: 
    value: 1200
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  clipavg: 
    value: 'view'
  geoloss: 
    values: [0]
  lr_decay: 
    values: [0.95]
  learning_rate:
    values: [0.0005]
  normratio:
    values: [0.05, 0.01] # different for NSF/BACON
  seed:
    values: [2022, 1990]
  pe: 
    value: 0
  frontview_std: 
    values: [4.0]
  frontview_elev_std: 
    values: [5.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 0
  model_name:
    values: ['RN50', 'ViT-B/32']
  divers_batch_aug:
    values: [1]
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    values: [2]
  colordepth:
    values: [2]
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    values: [NeuralStyleField]
  depth:
    values: [4]
  width:
    values: [256]
  sigma:
    values: [12, 5] # different for NSF/BACON
  n_views:
    values: [5] 
  background_image_mode:
    values: ['change_per_iter']