
program: main.py
name: pot_sweep_factory_S
project: item_sweep_factory
description: generating 3D stationary items
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss2_view
  goal: minimize
parameters:
  obj_path: 
    values: [/home/ali/text2mesh/astro_utils/collected_pot/2a534009a59513efe09958e15f14e5ca.obj,
            /home/ali/text2mesh/astro_utils/collected_pot/3ba7dd61736e7a96270c0e719fe4ed97.obj,
            /home/ali/text2mesh/astro_utils/collected_pot/3d2cafbf9a6a2da44212ff51b27f0221.obj]
  prompt: 
    values:  ["a photo of a luxury pot.", "a 3D rendering of a luxury pot.", "a photo of an old pot."]
  output_dir: 
    value: results/demo/pot/output
  n_iter: 
    value: 1200
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  clipavg: 
    value: 'view'
  geoloss: 
    values: [0]
  lr_decay: 
    values: [0.95]
  learning_rate:
    values: [0.0005]
  normratio:
    values: [0.005, 0.001]
  seed:
    values: [2022, 1990]
  pe: 
    value: 0
  frontview_std: 
    values: [1.0, 4.0, 10.0]
  frontview_elev_std: 
    values: [1.0, 2.0, 4.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 0
  model_name:
    values: ['RN50']
  divers_batch_aug:
    values: [1]
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    values: [3]
  colordepth:
    values: [3]
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    values: [BACON]
  depth:
    values: [8]
  width:
    values: [256]
  sigma:
    values: [448]
  n_views:
    values: [5] # 10 significantly improves the performance of the model.
  background_image_mode:
    values: ['change_per_iter']