
program: main.py
name: sink_sweep2_factory_S
project: item_sweep_factory
description: generating 3D stationary items
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss2_view
  goal: minimize
parameters:
  obj_path: 
    values: [/home/ali/text2mesh/astro_utils/collected_shapes/upsampled/sink/3_0.05_5_0.05/1fd3f0eb8e337ef7ac00fd1150223027.obj, 
             /home/ali/text2mesh/astro_utils/collected_shapes/upsampled/sink/3_0.05_5_0.05/2f7b32a0806ed5f09429f6a938b3978d.obj,
             /home/ali/text2mesh/astro_utils/collected_shapes/upsampled/sink/3_0.05_5_0.05/5c07f7040e822a42fdb729ff38860b34.obj]
  prompt: 
    values:  ["A photo of a luxury sink.", "A 3D rendering of a luxury sink.",
              "A photo of a marbel sink.", "A 3D rendering of a marbel sink.",
              "A photo of a black and white sink.", "A 3D rendering of a black and white sink.",
              "A photo of a golden sink.", "A 3D rendering of a golden sink.",
              "A photo of a gold and silver sink.", "A 3D rendering of a gold and silver sink."]
  output_dir: 
    value: results/demo/sink/output
  n_iter: 
    value: 1000
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  clipavg: 
    value: 'view'
  geoloss: 
    values: [0]
  lr_decay: 
    values: [0.95]
  learning_rate:
    values: [0.0005]
  normratio:
    values: [0.001]
  seed:
    values: [2022, 1990, 1991, 1, 2, 3]
  pe: 
    value: 0
  frontview_std: 
    values: [1.0]
  frontview_elev_std: 
    values: [1.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 0
  model_name:
    values: ['RN50x4', 'RN101']
  divers_batch_aug:
    values: [1]
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    values: [3]
  colordepth:
    values: [3]
  camera_r:
    value: 1.2
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    values: [BACON]
  depth:
    values: [8]
  width:
    values: [256]
  sigma:
    values: [448, 112]
  n_views:
    values: [5] # 10 significantly improves the performance of the model.
  background_image_mode:
    values: ['change_per_iter']