program: main.py
name: bacon_test
project: bacon_test
description: testing whether the BACON as the neaural style field improves the quality
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss
  goal: minimize
parameters:
  obj_path: 
    value: data/source_meshes/person.obj
  prompt: 
    values:  ["a 3D rendering of ninja in unreal engine", "a 3D rendering of Donald Trump in unreal engine", "a 3D rendering of Snoop Dogg in unreal engine", "a 3D rendering of batman in unreal engine"]
  output_dir: 
    value: results/demo/person/output
  n_iter: 
    value: 2000
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  frontview:
    value: 1
  clipavg: 
    value: 'view'
  geoloss: 
    value: 1
  lr_decay: 
    value: 1.0
  learning_rate:
    value: 0.0005
  normratio:
    value: 0.004
  seed:
    values: [29752, 542123, 678, 916, 1791990]
  pe: 
    value: 0
  frontview_std: 
    value: 4.0
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 1
  model_names:
    values: ['ViT-B/32']
  divers_batch_aug:
    value: 0
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    value: 2
  colordepth:
    value: 2
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    value: MultiscaleBACON
  depth:
    values: [8]
  width:
    values: [256, 512]
  sigma:
    values: [224, 112]
  
  


