program: main.py
name: bacon_shoe_facotry
project: bacon_shoe_facotry
description: generating static objects using BACON
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss_basic
  goal: minimize
parameters:
  obj_path: 
    value: data/source_meshes/shoe.obj
  prompt: 
    values:  ["a 3D rendering of a golden Nike Jordan.", "A 3D rendering of Jordan Shoes made for Super Mario."]
  output_dir: 
    value: results/demo/objs/output
  n_iter: 
    value: 2000
  n_augs:
    value: 2
  n_normaugs:
    value: 8
  # frontview:
    # value: 1
  clipavg: 
    value: 'view'
  geoloss: 
    value: 0
  lr_decay: 
    value: 1.0
  learning_rate:
    value: 0.0005
  normratio:
    values: [0.025, 0.01]
  seed:
    values: [29752, 542123]
  pe: 
    value: 0
  frontview_std: 
    values: [4.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 0
  model_name:
    values: ['RN50x16', 'ViT-B/16']
  divers_batch_aug:
    value: 1
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    value: 2
  colordepth:
    value: 2
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    value: MultiscaleBACON
  depth:
    values: [8]
  width:
    values: [256]
  sigma:
    values: [512, 128]
  n_views:
    values: [3]
  