program: main.py
name: bacon_obj_facotry
project: bacon_obj_facotry
description: generating static objects using BACON
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss
  goal: minimize
parameters:
  obj_path: 
    value: data/source_meshes/shoe.obj
  prompt: 
    values:  ["a 3D rendering of a rainbow Nike Jordan in unreal engine.", "a 3D rendering of a golden Nike Jordan in unreal engine.", "A 3D rendering of Jordan Shoes made for Super Mario in unreal engine."]
  output_dir: 
    value: results/demo/objs/output
  n_iter: 
    value: 2000
  n_augs:
    value: 5
  n_normaugs:
    value: 20
  frontview:
    value: 1
  clipavg: 
    value: 'view'
  geoloss: 
    value: 0
  lr_decay: 
    value: 1.0
  learning_rate:
    value: 0.0004
  normratio:
    values: [0.004, 0.001]
  seed:
    values: [29752, 542123, 678]
  pe: 
    value: 0
  frontview_std: 
    values: [4.0, 40.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 0
  model_name:
    values: ['RN50x16', 'ViT-L/14']
  divers_batch_aug:
    value: 1
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    value: 2
  colordepth:
    value: 2
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    value: MultiscaleBACON
  depth:
    values: [8]
  width:
    values: [256]
  sigma:
    values: [336, 112]
  n_views:
    values: [1]
  