
program: main.py
name: bacon_gorrila_facotry3
project: bacon_gorrila_facotry3
description: generating Gorrila using BACON
method: grid #random
early_terminate: 
  type: hyperband
  min_iter: 600
metric:
  name: eval_clip_loss2_view
  goal: minimize
parameters:
  obj_path: 
    value: data/source_meshes/Monkeytag.obj
  prompt: 
    values:  ["a 3D rendering of a gorrila with a golden chain in unreal engine", "a 3D rendering of a legless gorrila with a golden chain, unreal engine",
              "a 3D rendering of a gorrila wearing a brown jacked, unreal engine", "a 3D rendering of a gorrila wearing a red jacked, unreal engine", 
              "a 3D rendering of a gorrila wearing a black jacked, unreal engine", "a 3D rendering of a monkey wearing a black jacked, unreal engine"]
  output_dir: 
    value: results/demo/gorilla/output
  n_iter: 
    value: 400
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  clipavg: 
    value: 'view'
  geoloss: 
    values: [0]
  lr_decay: 
    values: [0.8]
  learning_rate:
    values: [0.0005]
  normratio:
    values: [0.005, 0.01]
  seed:
    values: [1991, 1990]
  pe: 
    value: 0
  frontview_std: 
    values: [4.0]
  frontview_elev_std: 
    values: [10.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    value: 0.4
  standardize: 
    value: 0
  model_name:
    values: ['ViT-B/32:0,RN50x16:0']
  coeff_models_deviate:
    values: [0.25]
  divers_batch_aug:
    values: [0]
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    values: [2]
  colordepth:
    values: [2]
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    values: [BACON]
  depth:
    values: [8]
  width:
    values: [256]
  sigma:
    values: [224]
  n_views:
    values: [6]
  background_image_mode:
    values: ['change_per_iter']
  background_based_prompt:
    values: [0]
  # renderer_shape:
  #   values: [384]
  log_interval:
    value: 100

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --frontview_center
  - 1.57
  - 0.1

