program: main.py
name: candle_factory_sweep2
project: candle_factory
description: Generating candles using normal-BACON and ensembel CLIP
method: grid #random
# early_terminate: 
#   type: hyperband
#   min_iter: 150
metric:
  name: eval_clip_loss2_view
  goal: minimize
parameters:
  obj_path: 
    values: [data/source_meshes/candle.obj]
  prompt: 
    values: ["A 3D rendering of a marbel candle in Unreal Engine.", "A 3D rendering of a luxury candle in Unreal Engine.", "A 3D rendering of a fancy candle in Unreal Engine.", 
              "A 3D rendering of a wooden candle in Unreal Engine.", "A 3D rendering of a stained glass candle in Unreal Engine.", "A 3D rendering of a crochet candle in Unreal Engine.", 
              "A 3D rendering of a golden candle in Unreal Engine.", "A 3D rendering of super mario's candle in Unreal Engine.", "A 3D rendering of a classic candle in Unreal Engine.", 
              "A 3D rendering of a futuristic candle in Unreal Engine.", "A 3D rendering of a red and blue candle in Unreal Engine.", "A 3D rendering of a kitchen candle in Unreal Engine.", 
              "A 3D rendering of a bathroom candle in Unreal Engine.", "A 3D rendering of a women's candle in Unreal Engine.", "A 3D rendering of a man's candle in Unreal Engine.", 
              "A 3D rendering of a realistic candle in Unreal Engine.", "A 3D rendering of Adidas candle in Unreal Engine.", "A 3D rendering of Louis Vuitton candle in Unreal Engine.", 
              "A 3D rendering of Nike candle in Unreal Engine.", "A 3D rendering of Islamic candle in Unreal Engine.", "A 3D rendering of roman candle in Unreal Engine.",
              "Super Mario", "Snoop Dogg", "roman", "Nike", "Adidas"] ### HIGHLY ENCOURAGE TO ALWAYS ADD IN UNREAL ENGINE.
  output_dir: 
    value: obj_factory/candles/outputs
  n_iter: 
    value: 500
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  clipavg: 
    value: 'view'
  geoloss: 
    values: [0]
  lr_decay: 
    values: [0.85]
  learning_rate:
    values: [0.0005]
  normratio:
    values: [0.0025] # 0.002
  seed:
    values: [2022, 1990]
  pe: 
    value: 0
  frontview_std:  # 4.0
    values: [4.0]
  frontview_elev_std: 
    values: [1.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    values: [0.4]
  standardize: 
    value: 0
  model_name:
    values: ['ViT-B/32:0,RN50x16:0'] # ViT-B/16
  coeff_models_deviate:
    values: [0.3]
  divers_batch_aug:
    values: [0]
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    values: [2]
  colordepth:
    values: [2]
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    values: [BACON]
  depth:
    values: [8]
  width:
    values: [256, 512] # 512
  sigma:
    values: [224] # 224
  n_views:
    values: [5] 
  background_image_mode:
    values: ['change_per_iter']
  background_based_prompt:
    values: [0]
  # renderer_shape:
  #   values: [384]
  log_interval:
    value: 50

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --frontview_center
  - 0
  - 0