program: main.py
name: chair_factory_sweep
project: chair_factory
description: Generating chairs using normal-BACON and ensembel CLIP
method: grid #random
# early_terminate: 
#   type: hyperband
#   min_iter: 150
metric:
  name: eval_clip_loss2_view
  goal: minimize
parameters:
  obj_path: 
    values: [data/brute_force_no_culling_rotated/chair1_1b05971a4373c7d2463600025db2266.obj,
             data/brute_force_no_culling_rotated/chair2_155dfcdcc387b025492d9da2668ec34c.obj,
             data/brute_force_no_culling_rotated/chair3_111720e8cd4c613492d9da2668ec34c.obj]
  prompt: 
    values: ["A 3D rendering of a marbel chair in Unreal Engine.", "A 3D rendering of a luxury chair in Unreal Engine.", "A 3D rendering of a fancy chair in Unreal Engine.", 
            "A 3D rendering of a wooden chair in Unreal Engine.", "A 3D rendering of a stained glass chair in Unreal Engine.", "A 3D rendering of a crochet chair in Unreal Engine.", 
            "A 3D rendering of a golden chair in Unreal Engine.", "A 3D rendering of a classic chair in Unreal Engine.", "A 3D rendering of a futuristic chair in Unreal Engine.", 
            "A 3D rendering of a red and blue chair in Unreal Engine.", "A 3D rendering of a green and yellow chair in Unreal Engine.", "A 3D rendering of Snoop Dogg's chair in Unreal Engine.", 
            "A 3D rendering of Super Mario's chair in Unreal Engine.", "A 3D rendering of Batman's chair in Unreal Engine.", "A 3D rendering of a women's chair in Unreal Engine.", 
            "A 3D rendering of a man's chair in Unreal Engine.", "A 3D rendering of a roman's chair in Unreal Engine.", "A 3D rendering of a military chair in Unreal Engine.", 
            "A 3D rendering of a sport chair in Unreal Engine.", "A 3D rendering of Adidas chair in Unreal Engine.", "A 3D rendering of Louis Vuitton chair in Unreal Engine.", 
            "A 3D rendering of Nike chair in Unreal Engine.", "A 3D rendering of Gucci chair in Unreal Engine.", "A 3D rendering of Lacoste chair in Unreal Engine.", 
            "A marbel chair.", "A luxury chair.", "A fancy chair.", 
            "A wooden chair.", "A stained glass chair.", "A crochet chair.", "A golden chair.", 
            "A classic chair.", "A futuristic chair.", "A red and blue chair.", "A green and yellow chair.", 
            "Snoop dogg's chair.", "Super mario's chair.", "Batman's chair.", "A women's chair.", 
            "A man's chair.", "A roman's chair.", "A military chair.", "A sport chair.", 
            "Adidas chair.", "Louis vuitton chair.", "Nike chair.", "Gucci chair.", "Lacoste chair.",
            "Super Mario", "Snoop Dogg", "roman", "Nike", "Adidas", "Gucci", "Lacoste", "Army", "Military"] ### HIGHLY ENCOURAGE TO ALWAYS ADD IN UNREAL ENGINE.
  output_dir: 
    value: obj_factory/lamp/outputs
  n_iter: 
    value: 500
  n_augs:
    value: 1
  n_normaugs:
    value: 4
  clipavg: 
    value: 'view'
  geoloss: 
    values: [0]
  lr_decay: 
    values: [0.85]
  learning_rate:
    values: [0.0005]
  normratio:
    values: [0.003] # 0.002
  seed:
    values: [2022, 1990]
  pe: 
    value: 0
  frontview_std:  # 4.0
    values: [4.0]
  frontview_elev_std: 
    values: [1.0]
  normmincrop:
    value: 0.1
  normmaxcrop: 
    values: [0.4]
  standardize: 
    value: 0
  model_name:
    values: ['ViT-B/32:0,RN50x16:0'] # ViT-B/16
  coeff_models_deviate:
    values: [0.3]
  divers_batch_aug:
    values: [0]
  symmetry:
    value: 1
  maxcrop:
    value: 1.0
  normdepth:
    values: [2]
  colordepth:
    values: [2]
  camera_r:
    value: 1.0
  mesh_normalizer_func:
    value: 'min_max'
  neural_style_field:
    values: [BACON]
  depth:
    values: [8]
  width:
    values: [384] # 512
  sigma:
    values: [224] # 224
  n_views:
    values: [5] 
  background_image_mode:
    values: ['change_per_iter']
  background_based_prompt:
    values: [0]
  # renderer_shape:
  #   values: [384]
  log_interval:
    value: 100

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --frontview_center
  - 1.57
  - 0.1